services:
  - type: web
    name: cosmos-exoplanet-app
    runtime: python
    buildCommand: "python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python -m src.ml.train"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
